[package]
name = "cargo-finestra"
edition.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
