[package]
name = "showcase"
edition.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
finestra = { path = "../finestra" }
